version: '3'

networks:
  ics:
    name: ics
    driver: bridge
    ipam:
      config: 
        - subnet: 192.168.192.0/24

services:

  tshark:
    image: oihan27/tshark:tshark
    build: 
      context: ./Tshark
    container_name: tshark
    volumes:
      - /Tshark:/home/captures
    privileged: true
    network_mode: host
    restart: unless-stopped

  interface:
    image: frolvlad/alpine-gxx
    container_name: interface
    command: sh -c "g++ /Interface/simlink.cpp -o Interface/simlink -pthread && tail -F /dev/null" #Ejecuta el archivo .cpp con la ayuda del .cfg
    volumes: 
      - ./wwtp/interface_simLink:/Interface
    restart: unless-stopped
    networks:
      ics:
        ipv4_address: 192.168.192.2

  matlab_simulink: #Contiene el programa de Matlab/Simulink
    image: sflorenz05/matlab_simulink:v0.3
    container_name: matlab_simulink
    shm_size: 512M
    ports:
      - "5901:5901"
      - "6080:6080"
    command: -vnc
    volumes:
      - ./wwtp/simulink:/home/matlab/Documents/MATLAB/simulink
    restart: unless-stopped
    networks:
      ics:
        ipv4_address: 192.168.192.4
